---
- name: Create path /var/www/autoconfig
  file:
    path: /var/www/autoconfig
    state: directory
    mode: '0755'

- name: Clone repository
  git:
    repo: https://github.com/stuvusIT/MailClientAutoConfig
    dest: /var/www/autoconfig
    depth: 1
    update: true

- name: Place autoconfig.php
  template:
    src: autoconfig.settings.php.j2
    dest: /var/www/autoconfig/src/autoconfig.settings.php
    owner: root
    group: www-data
    mode: '0644'
